; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc1-n16r8]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc1-n16r8
framework = arduino
lib_deps = 
	maxint-rd/TM16xx LEDs and Buttons@^0.7.2512
	tanakamasayuki/efont Unicode Font Data@^1.0.9
	adafruit/Adafruit GFX Library@^1.12.6
monitor_speed = 115200
upload_speed = 1500000
build_type = debug
build_flags = -DARDUINO_USB_CDC_ON_BOOT=1 -DARDUINO_USB_MODE=1
